### ISSUE TITLE
Show waveform within certain amount of time windown

### ISSUE THREAD

**Issue by comoglu** [usgs/swarm#213]
Is that possible to display for example 40 of preselected stations or selecting stations from  GUI to display by giving start and engine?

**Comment by comoglu** [comment]
This feature would be very useful for Seismologist to check aftershocks or daily seismicity for some set of stations. Daily plots are also very useful however you have to open station one by one. Instead open for i.g 6 hours of a set of stations and scroll in time would be good approach.

**Comment by dnorgaard-usgs** [comment]
Hi.  Have you tried the layout feature in Swarm?  If you pre-select your stations into the clipboard (or monitor) and save as a layout, you can open the layout in future and it should pre-populate the clipboard (or monitor) with the saved stations.

**Comment by dnorgaard-usgs** [comment]
The layout feature should address this.  Please reopen if issue is misunderstood.

**Comment by comoglu** [comment]
yes, I tried of course but I was trying to say; a window to display several stations (pre-selected)(This is Ok with saving layout) for e.g 3-6-12 hours or/else to give some time interval in the past to display those preselected stations on @Monitor@ Window

**Comment by comoglu** [comment]
> The layout feature should address this. Please reopen if issue is misunderstood.

I guess I cannot open this ticket on my own?

**Comment by dnorgaard-usgs** [comment]
The Monitoring window was designed to continuously retrieve new data and move forward in time.  It's not really possible to go back in time there since soon as there is new data, it will scroll to the current time.  What you can do though is set the Time Span in Monitor Settings.  It goes up to 2 hours (7200 seconds). The wave data in the clipboard is a little more flexible with displaying past data.
